import { useCallback, useEffect, useState, useRef } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/components/auth/AuthProvider";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { ArrowRight, Check, Zap, RefreshCw, Clock, Sparkles, MessageCircle } from "lucide-react";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import { motion, AnimatePresence } from "framer-motion";
import { getWeek, getYear } from "date-fns";

import { DayCompleteRecommendations } from "@/components/dashboard/DayCompleteRecommendations";
import { FirstTimeTooltip } from "@/components/dashboard/FirstTimeTooltip";
import { WeaveLoader } from "@/components/ui/weave-loader";

const Dashboard = () => {
  const { user } = useAuth();
  const [todayTask, setTodayTask] = useState<any>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [currentSequence, setCurrentSequence] = useState(1);
  const [tasksForToday, setTasksForToday] = useState<any[]>([]);
  
  // Next Best Rep state
  const [isGettingRep, setIsGettingRep] = useState(false);
  const [nextRep, setNextRep] = useState<any>(null);
  const [showRepDialog, setShowRepDialog] = useState(false);
  
  // Active experiment state
  const [activeExperiment, setActiveExperiment] = useState<any>(null);
  
  // Identity state
  const [identitySeed, setIdentitySeed] = useState<string | null>(null);
  const [yearNote, setYearNote] = useState<string | null>(null);
  const [userName, setUserName] = useState<string | null>(null);
  const [isFirstTime, setIsFirstTime] = useState(false);
  
  
  // Skip / recalibration
  const [isSkipping, setIsSkipping] = useState(false);
  const [sessionSkipCount, setSessionSkipCount] = useState(0);
  const [showRecalibration, setShowRecalibration] = useState(false);
  const [recalibrationText, setRecalibrationText] = useState('');
  
  // Auto-generate on first load
  const hasAutoGenerated = useRef(false);

  const getLocalToday = () => {
    const now = new Date();
    return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`;
  };

  const isTaskStale = (task: any) => {
    if (!task?.created_at) return false;
    const taskCreated = new Date(task.created_at);
    const now = new Date();
    const hoursSinceCreation = (now.getTime() - taskCreated.getTime()) / (1000 * 60 * 60);
    
    const getTimeOfDay = (hour: number) => {
      if (hour >= 5 && hour < 12) return 'morning';
      if (hour >= 12 && hour < 17) return 'afternoon';
      if (hour >= 17 && hour < 21) return 'evening';
      return 'night';
    };
    
    return getTimeOfDay(taskCreated.getHours()) !== getTimeOfDay(now.getHours()) && hoursSinceCreation > 4 && !task.completed;
  };

  const getTimePhase = () => {
    const hour = new Date().getHours();
    if (hour >= 5 && hour < 12) return 'morning';
    if (hour >= 12 && hour < 17) return 'afternoon';
    if (hour >= 17 && hour < 21) return 'evening';
    return 'night';
  };

  const getGreeting = () => {
    const name = userName?.split(' ')[0];
    return name || '';
  };

  const fetchData = useCallback(async () => {
    if (!user) return;

    const today = getLocalToday();

    const [identityRes, profileRes] = await Promise.all([
      supabase
        .from("identity_seeds")
        .select("content, year_note")
        .eq("user_id", user.id)
        .maybeSingle(),
      supabase
        .from("profiles")
        .select("full_name")
        .eq("id", user.id)
        .maybeSingle()
    ]);
    
    if (identityRes.data?.content) setIdentitySeed(identityRes.data.content);
    if (identityRes.data?.year_note) setYearNote(identityRes.data.year_note);
    if (profileRes.data?.full_name) setUserName(profileRes.data.full_name);

    const { data: tasksRes } = await supabase
      .from("daily_tasks")
      .select("*")
      .eq("user_id", user.id)
      .eq("task_date", today)
      .order("task_sequence", { ascending: true });

    if (tasksRes && tasksRes.length > 0) {
      const incomplete = tasksRes.find((t) => !t.completed);

      if (incomplete && isTaskStale(incomplete)) {
        await supabase.from("daily_tasks").delete().eq("id", incomplete.id);
        const remainingTasks = tasksRes.filter((t) => t.id !== incomplete.id);
        setTasksForToday(remainingTasks);
        setTodayTask(null);
        setCurrentSequence(remainingTasks.length + 1);
        return;
      }

      setTasksForToday(tasksRes);
      setCurrentSequence(incomplete?.task_sequence || tasksRes.length);
      setTodayTask(incomplete || tasksRes[tasksRes.length - 1]);
      setIsFirstTime(false);
    } else {
      setTasksForToday([]);
      setTodayTask(null);
      setCurrentSequence(1);
      const { count } = await supabase
        .from("daily_tasks")
        .select("id", { count: 'exact', head: true })
        .eq("user_id", user.id);
      setIsFirstTime(count === 0);
    }

    const { data: expRes } = await supabase
      .from("experiments")
      .select("*")
      .eq("user_id", user.id)
      .eq("status", "in_progress")
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle();

    setActiveExperiment(expRes);
  }, [user]);

  useEffect(() => {
    if (!user) return;
    fetchData();

    const midnightCheck = setInterval(() => {
      const today = getLocalToday();
      if (tasksForToday.length > 0 && tasksForToday[0]?.task_date !== today) {
        setTasksForToday([]);
        setTodayTask(null);
        setCurrentSequence(1);
        hasAutoGenerated.current = false;
      }
    }, 60000);

    const channelName = `dashboard-tasks-${user.id}`;
    const taskChannel = supabase
      .channel(channelName)
      .on(
        "postgres_changes",
        { event: "*", schema: "public", table: "daily_tasks", filter: `user_id=eq.${user.id}` },
        () => fetchData(),
      )
      .subscribe();

    return () => {
      clearInterval(midnightCheck);
      supabase.removeChannel(taskChannel);
    };
  }, [user, fetchData]);

  // Auto-generate first invitation on mount if none exists
  useEffect(() => {
    if (!user || hasAutoGenerated.current || isGenerating) return;
    if (tasksForToday.length === 0 && !todayTask && identitySeed !== null) {
      hasAutoGenerated.current = true;
      handleGenerateTask();
    }
  }, [user, tasksForToday, todayTask, identitySeed]);

  const handleGenerateTask = async (contextOverride?: { energy?: string; time?: string }) => {
    if (!user || isGenerating) return;
    
    setIsGenerating(true);
    const today = getLocalToday();
    
    try {
      const { data: existingTasks } = await supabase
        .from("daily_tasks")
        .select("id, task_sequence")
        .eq("user_id", user.id)
        .eq("task_date", today)
        .order("task_sequence", { ascending: false });
      
      if (existingTasks && existingTasks.length >= 4) {
        toast.info("All invitations done for today");
        return;
      }
      
      const maxSeq = existingTasks?.[0]?.task_sequence || 0;
      const nextSequence = maxSeq + 1;
      const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
      
      const { data, error } = await supabase.functions.invoke("navigator", {
        body: { 
          timezone,
          rejectionCount: sessionSkipCount,
          openQuestion: recalibrationText || undefined
        }
      });
      if (error) throw error;
      
      if (data) {
        const { error: insertError } = await supabase
          .from("daily_tasks")
          .insert({
            user_id: user.id,
            task_date: today,
            task_sequence: nextSequence,
            title: data.priority_for_today || "Action",
            one_thing: data.do_this_now,
            why_matters: data.why_it_matters,
            description: data.time_required,
            pillar: data.priority_for_today,
            completed: false,
          });

        if (insertError) {
          if (insertError.code === "23505") {
            await fetchData();
            return;
          }
          throw insertError;
        }
        await fetchData();
      }
    } catch (error: any) {
      console.error("Generate error:", error);
      toast.error(error.message || "Failed to generate");
    } finally {
      setIsGenerating(false);
    }
  };

  const handleCompleteTask = async () => {
    if (!todayTask || !user) return;
    
    try {
      const today = getLocalToday();
      
      const { error: updateError } = await supabase
        .from("daily_tasks")
        .update({ completed: true })
        .eq("user_id", user.id)
        .eq("task_date", today)
        .eq("task_sequence", currentSequence);

      if (updateError) throw updateError;

      const updatedTasks = tasksForToday.map(t => 
        t.task_sequence === currentSequence ? { ...t, completed: true } : t
      );
      setTasksForToday(updatedTasks);
      
      const now = new Date();
      await supabase.from('user_activity_patterns').insert({
        user_id: user.id,
        hour_of_day: now.getHours(),
        day_of_week: now.getDay(),
        activity_type: 'complete',
        pillar: todayTask?.priority_for_today
      });

      // Auto-complete matching weekly intentions
      const taskText = todayTask?.do_this_now?.toLowerCase() || '';
      if (taskText) {
        try {
          const weekNumber = getWeek(now, { weekStartsOn: 1 });
          const year = getYear(now);
          const { data: weeklyIntentions } = await supabase
            .from('weekly_intentions')
            .select('id, text, completed')
            .eq('user_id', user.id)
            .eq('week_number', weekNumber)
            .eq('year', year)
            .eq('completed', false);
          
          if (weeklyIntentions) {
            for (const intention of weeklyIntentions) {
              const intentionWords = intention.text.toLowerCase().split(/\s+/).filter((w: string) => w.length > 3);
              const matchCount = intentionWords.filter((w: string) => taskText.includes(w)).length;
              // If 50%+ of meaningful words match, auto-complete it
              if (intentionWords.length > 0 && matchCount / intentionWords.length >= 0.5) {
                await supabase
                  .from('weekly_intentions')
                  .update({ completed: true })
                  .eq('id', intention.id);
              }
            }
          }
        } catch (e) {
          console.error('Auto-complete intentions error:', e);
        }
      }

      const completedNow = updatedTasks.filter(t => t.completed).length;
      
      if (completedNow < 3) {
        toast.success("Done. Next one coming...");
        setTodayTask(null);
        setCurrentSequence(completedNow + 1);
        await handleGenerateTask();
      } else if (currentSequence === 4) {
        toast.success("Bonus complete.");
        setTodayTask(null);
      } else {
        toast.success("All 3 done.");
        setTodayTask(null);
      }
    } catch (error: any) {
      console.error("Complete error:", error);
      toast.error(error.message || "Failed to complete");
    }
  };

  const handleNextRep = async () => {
    setIsGettingRep(true);
    try {
      const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
      const { data, error } = await supabase.functions.invoke("next-rep", {
        body: { timezone }
      });
      if (error) throw error;
      if (data) {
        setNextRep(data);
        setShowRepDialog(true);
      }
    } catch (error: any) {
      toast.error(error.message || "Failed to get rep");
    } finally {
      setIsGettingRep(false);
    }
  };

  const handleSkipTask = async () => {
    if (!todayTask || !user || isSkipping) return;
    
    setIsSkipping(true);
    try {
      const now = new Date();
      await supabase.from('user_activity_patterns').insert({
        user_id: user.id,
        hour_of_day: now.getHours(),
        day_of_week: now.getDay(),
        activity_type: 'skip',
        pillar: todayTask?.pillar
      });
      
      await supabase.from("daily_tasks").delete().eq("id", todayTask.id);
      
      const newSkipCount = sessionSkipCount + 1;
      setSessionSkipCount(newSkipCount);
      setTodayTask(null);
      
      if (newSkipCount >= 2) {
        setShowRecalibration(true);
        toast.info("Let's recalibrate");
      } else {
        toast.info("Finding something better...");
        await handleGenerateTask();
      }
    } catch (error: any) {
      console.error("Skip error:", error);
      toast.error("Failed to skip");
    } finally {
      setIsSkipping(false);
    }
  };

  const completedCount = tasksForToday.filter(t => t.completed).length;
  const threeComplete = completedCount >= 3;
  const allDone = completedCount >= 4 || (threeComplete && !tasksForToday.some(t => t.task_sequence === 4));
  const showBonusOption = threeComplete && completedCount === 3 && !tasksForToday.some(t => t.task_sequence === 4);
  const dotsToShow = tasksForToday.some(t => t.task_sequence === 4) ? 4 : 3;

  return (
    <div className="min-h-screen flex flex-col max-w-lg mx-auto px-4 py-6 animate-fade-in overflow-x-hidden w-full">
      {user && (
        <>
          <FirstTimeTooltip userId={user.id} isFirstTime={isFirstTime} />
          <DayCompleteRecommendations userId={user.id} isComplete={allDone} />
        </>
      )}

      <div className="flex-1 space-y-5">

        {/* The Knowing Nudge */}
        <section className="relative">
          {/* Progress dots */}
          {tasksForToday.length > 0 && (
            <div className="absolute -top-1 right-3 flex items-center gap-1.5 z-10">
              {Array.from({ length: dotsToShow }, (_, i) => i + 1).map((num) => {
                const isCompleted = tasksForToday.some(t => t.task_sequence === num && t.completed);
                const isCurrent = num === currentSequence && !allDone;
                return (
                  <motion.div
                    key={num}
                    initial={false}
                    animate={{ 
                      scale: isCurrent ? 1.2 : 1,
                      backgroundColor: isCompleted 
                        ? 'hsl(var(--primary))' 
                        : isCurrent 
                          ? 'hsl(var(--primary) / 0.5)' 
                          : 'hsl(var(--muted-foreground) / 0.2)'
                    }}
                    className="w-2 h-2 rounded-full"
                  />
                );
              })}
            </div>
          )}

          <div className="rounded-3xl border border-border/40 bg-gradient-to-br from-card via-card to-muted/30 overflow-hidden relative">
            {/* Subtle texture */}
            <div className="absolute inset-0 opacity-[0.015] pointer-events-none">
              <svg className="w-full h-full" xmlns="http://www.w3.org/2000/svg">
                <pattern id="weave" x="0" y="0" width="40" height="40" patternUnits="userSpaceOnUse">
                  <path d="M0 20h40M20 0v40" stroke="currentColor" strokeWidth="0.5" fill="none"/>
                </pattern>
                <rect width="100%" height="100%" fill="url(#weave)"/>
              </svg>
            </div>

            <AnimatePresence mode="wait">
              {isGenerating && !todayTask ? (
                <motion.div
                  key="loading"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="p-8 py-20 flex flex-col items-center justify-center relative"
                >
                  <WeaveLoader size="lg" text={
                    getTimePhase() === 'morning' ? "Weaving your morning..." :
                    getTimePhase() === 'afternoon' ? "Reading your week..." :
                    getTimePhase() === 'evening' ? "Checking what's unfinished..." :
                    "Pulling the thread..."
                  } />
                </motion.div>
              ) : showBonusOption ? (
                <motion.div
                  key="bonus"
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="p-8 py-14 text-center space-y-5 relative"
                >
                  <div className="space-y-2">
                    <h2 className="text-2xl font-display font-semibold">Three done.</h2>
                    <p className="text-muted-foreground text-sm">You showed up. That compounds.</p>
                  </div>
                  <Button
                    variant="outline"
                    size="lg"
                    onClick={() => handleGenerateTask({})}
                    className="rounded-2xl h-12 px-6"
                  >
                    One more
                  </Button>
                </motion.div>
              ) : allDone ? (
                <motion.div
                  key="done"
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="p-8 py-16 text-center space-y-3 relative"
                >
                  {getTimePhase() === 'afternoon' ? (
                    <p className="text-base text-muted-foreground leading-relaxed">
                      Done for today. Go live it.
                    </p>
                  ) : getTimePhase() === 'evening' ? (
                    <p className="text-base text-muted-foreground leading-relaxed">
                      You moved today. Rest now.
                    </p>
                  ) : (
                    <p className="text-base text-muted-foreground leading-relaxed">
                      Done. That matters.
                    </p>
                  )}
                </motion.div>
              ) : todayTask ? (
                <motion.div
                  key="task"
                  initial={{ opacity: 0, y: 8 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.4, ease: "easeOut" }}
                  className="relative"
                >
                  {/* The nudge — like a text from someone who knows you */}
                  <div className="p-6 pb-0">
                    <div className="flex items-start justify-between mb-5">
                      <div className="flex items-center gap-2">
                        {todayTask.pillar && (
                          <span className="inline-block px-2.5 py-1 rounded-lg text-[11px] font-medium bg-primary/8 text-primary/80">
                            {todayTask.pillar}
                          </span>
                        )}
                        {todayTask.description && (
                          <span className="text-[11px] text-muted-foreground/60 flex items-center gap-1">
                            <Clock className="h-3 w-3" />
                            {todayTask.description}
                          </span>
                        )}
                      </div>
                      <button
                        onClick={handleSkipTask}
                        disabled={isSkipping}
                        className="text-[11px] text-muted-foreground/40 hover:text-muted-foreground transition-colors"
                      >
                        {isSkipping ? "..." : getTimePhase() === 'evening' || getTimePhase() === 'night' ? "pass" : "not today"}
                      </button>
                    </div>
                    
                    {/* The action — clear, specific, conversational */}
                    <h2 className="text-xl font-display font-semibold leading-snug mb-3">
                      {todayTask.one_thing}
                    </h2>
                    
                    {/* The why — the knowing part */}
                    {todayTask.why_matters && (
                      <p className="text-sm text-muted-foreground/80 leading-relaxed mb-5">
                        {todayTask.why_matters}
                      </p>
                    )}
                  </div>
                  
                  {/* Single action */}
                  <div className="p-6 pt-0">
                    <Button 
                      onClick={handleCompleteTask} 
                      className="w-full h-12 rounded-2xl text-base font-medium shadow-soft hover:shadow-elevated transition-all"
                      size="lg"
                    >
                      Done <Check className="ml-2 h-4 w-4" />
                    </Button>
                  </div>
                </motion.div>
              ) : showRecalibration ? (
                <motion.div
                  key="recalibrate"
                  initial={{ opacity: 0, y: 8 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="p-6 space-y-4 relative"
                >
                  <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-primary/15 to-primary/5 flex items-center justify-center">
                    <MessageCircle className="h-5 w-5 text-primary" />
                  </div>
                  <p className="text-sm text-muted-foreground">
                    Those didn't land. What feels alive right now?
                  </p>
                  <Textarea
                    value={recalibrationText}
                    onChange={(e) => setRecalibrationText(e.target.value)}
                    placeholder="What's actually on your mind..."
                    className="min-h-[80px] rounded-2xl text-sm resize-none bg-muted/30 border-border/40"
                  />
                  <Button
                    size="lg"
                    onClick={() => {
                      setShowRecalibration(false);
                      handleGenerateTask({});
                    }}
                    disabled={!recalibrationText.trim()}
                    className="w-full h-12 rounded-2xl"
                  >
                    Recalibrate
                    <ArrowRight className="ml-2 h-4 w-4" />
                  </Button>
                </motion.div>
              ) : (
                <motion.div
                  key="empty"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className="p-8 py-16 text-center space-y-5 relative"
                >
                  {isFirstTime && identitySeed ? (
                    <>
                      <p className="text-sm text-muted-foreground leading-relaxed max-w-xs mx-auto">
                        {identitySeed.length > 120 ? identitySeed.substring(0, 120) + '...' : identitySeed}
                      </p>
                      <Button
                        onClick={() => handleGenerateTask()}
                        size="lg"
                        className="px-8 h-13 rounded-2xl text-base font-medium shadow-soft hover:shadow-elevated transition-all gap-2"
                      >
                        <Sparkles className="h-4 w-4" />
                        First invitation
                      </Button>
                    </>
                  ) : (
                    <Button
                      onClick={() => handleGenerateTask()}
                      size="lg"
                      className="px-8 h-13 rounded-2xl text-base font-medium shadow-soft hover:shadow-elevated transition-all gap-2"
                    >
                      <Sparkles className="h-4 w-4" />
                      What's next?
                    </Button>
                  )}
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </section>

        {/* Current Chapter */}
        {activeExperiment && (
          <section className="px-1">
            {(() => {
              const createdDate = new Date(activeExperiment.created_at);
              const now = new Date();
              const startDay = new Date(createdDate.getFullYear(), createdDate.getMonth(), createdDate.getDate());
              const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
              const dayNumber = Math.floor((today.getTime() - startDay.getTime()) / (1000 * 60 * 60 * 24)) + 1;
              
              const durationStr = activeExperiment.duration?.toLowerCase() || '';
              let totalDays = 7;
              if (durationStr.includes('48h') || durationStr.includes('2 day')) totalDays = 2;
              else if (durationStr.includes('24h') || durationStr.includes('1 day')) totalDays = 1;
              else if (durationStr.includes('3 day')) totalDays = 3;
              else if (durationStr.includes('5 day')) totalDays = 5;
              else if (durationStr.includes('week')) totalDays = 7;
              else if (durationStr.includes('2 week')) totalDays = 14;

              // Extract what to notice today from steps
              const steps = activeExperiment.steps?.split('\n').filter((s: string) => s.trim()) || [];
              let todayFocus = '';
              if (steps.length > 0) {
                todayFocus = steps[Math.min(dayNumber - 1, steps.length - 1)] || '';
              }
              
              return (
                <div className="space-y-2">
                  <p className="text-[10px] text-muted-foreground/50 uppercase tracking-widest pl-1">
                    Current chapter · day {dayNumber}
                  </p>
                  <p className="text-sm text-muted-foreground leading-relaxed">
                    You're testing: <span className="text-foreground font-medium">{activeExperiment.identity_shift_target || activeExperiment.title}</span>
                  </p>
                  {todayFocus && getTimePhase() !== 'evening' && getTimePhase() !== 'night' && (
                    <p className="text-xs text-muted-foreground/60 leading-relaxed">
                      {todayFocus}
                    </p>
                  )}
                </div>
              );
            })()}
          </section>
        )}

        <button
          onClick={handleNextRep}
          disabled={isGettingRep}
          className="w-full group text-left"
        >
          <div className="flex items-center gap-4 p-5 rounded-2xl border border-border/40 bg-gradient-to-r from-card/60 to-muted/20 hover:from-card hover:to-muted/30 hover:border-primary/20 transition-all">
            <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-primary/20 to-primary/5 flex items-center justify-center group-hover:from-primary/30 group-hover:to-primary/10 transition-colors shrink-0">
              <Zap className="h-5 w-5 text-primary" />
            </div>
            <div className="flex-1 min-w-0">
              <p className="font-semibold text-base">
                {isGettingRep ? "Finding your next move..." : "Need a reset?"}
              </p>
              <p className="text-sm text-muted-foreground">
                One tap. One aligned action.
              </p>
            </div>
            <ArrowRight className="h-5 w-5 text-muted-foreground group-hover:text-primary group-hover:translate-x-0.5 transition-all flex-shrink-0" />
          </div>
        </button>
      </div>

      {/* Next Best Rep Dialog */}
      <Dialog open={showRepDialog} onOpenChange={setShowRepDialog}>
        <DialogContent className="max-w-sm rounded-3xl border-border/50">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 text-lg font-display">
              <Zap className="h-4 w-4 text-primary" />
              {nextRep?.bucket || "Your Rep"}
            </DialogTitle>
            <DialogDescription className="text-muted-foreground">Break the drift</DialogDescription>
          </DialogHeader>
          {nextRep && (
            <div className="space-y-5 pt-2">
              <p className="text-lg font-medium leading-relaxed">{nextRep.rep}</p>
              <p className="text-sm text-muted-foreground">{nextRep.why}</p>
              <div className="flex items-center justify-between text-xs text-muted-foreground pt-3 border-t border-border">
                <span>{nextRep.time}</span>
                <span className="px-2 py-1 rounded-lg bg-muted font-medium">{nextRep.bucket}</span>
              </div>
              <Button onClick={() => setShowRepDialog(false)} className="w-full h-12 rounded-2xl">
                Got it
              </Button>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default Dashboard;
